<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Thm vo gi_img-loop image-product-loop b_e6f1b6_1</name>
   <tag></tag>
   <elementGuidId>eb812158-97c4-4223-b239-b1cd66d787a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collection-body']/div/div[2]/div[3]/div[3]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>38b5e792-d53a-443f-9f67-2d98773c5a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-loop image-product-loop bigloaded</value>
      <webElementGuid>c5fd30d8-e92a-428a-97a7-bc3eb4d2bf3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mô hình Blind box Gấu bông Baby Three Lucky Cat Zipper Bag Series ( Mèo Thần Tài ) BABY THREE</value>
      <webElementGuid>b10170bd-09cd-4302-a84a-631e5e426c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/ind-box-gau-bong-baby-three-lucky-cat-zipper-bag-series-baby-three__1__4d2c63bc12cf47b6a6ee78f0d6d4efd7_large.jpg</value>
      <webElementGuid>f4cd63ae-69e1-42d6-9f7d-f2998019f80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>8e8d1706-4387-45f5-abf4-6b86d0a014e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>82255ebf-c38f-4cc3-9189-bf3b14a64fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/ind-box-gau-bong-baby-three-lucky-cat-zipper-bag-series-baby-three__1__4d2c63bc12cf47b6a6ee78f0d6d4efd7_large.jpg</value>
      <webElementGuid>5915e5ba-0f7b-43ff-b589-a2c3e4483011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-body&quot;)/div[@class=&quot;col-sm-8 col-xs-12&quot;]/div[@class=&quot;row filter-here&quot;]/div[@class=&quot;content-product-list collection-list clearfix&quot;]/div[@class=&quot;pro-loop animation-tran active&quot;]/div[@class=&quot;product-block  pro-new&quot;]/div[@class=&quot;product-img img-eff&quot;]/a[@class=&quot;image-resize&quot;]/img[@class=&quot;img-loop image-product-loop bigloaded&quot;]</value>
      <webElementGuid>99b0a1fb-b52e-478c-9965-432cf4818ceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div[3]/div/div/a/img</value>
      <webElementGuid>3be29cfd-be34-4f60-a1f3-be06d5989ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mô hình Blind box Gấu bông Baby Three Lucky Cat Zipper Bag Series ( Mèo Thần Tài ) BABY THREE']</value>
      <webElementGuid>dc2b13a7-8b9f-4ff1-bb12-34e187ee597d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/img</value>
      <webElementGuid>398b294d-20f7-4b4a-9342-801378e99685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Mô hình Blind box Gấu bông Baby Three Lucky Cat Zipper Bag Series ( Mèo Thần Tài ) BABY THREE' and @src = '//product.hstatic.net/200000726533/product/ind-box-gau-bong-baby-three-lucky-cat-zipper-bag-series-baby-three__1__4d2c63bc12cf47b6a6ee78f0d6d4efd7_large.jpg']</value>
      <webElementGuid>b7391c2f-635f-403f-9e37-c7dfe6600790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
