<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Thm vo gi_img-loop image-product-loop b_e6f1b6</name>
   <tag></tag>
   <elementGuidId>865107d5-a5e2-48f8-b73b-160d4c38d272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collection-body']/div/div[2]/div[3]/div[3]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e28d46a0-d3e9-4524-aae6-3820d1ce0c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-loop image-product-loop bigloaded</value>
      <webElementGuid>3f4fcba3-ca6e-4f76-98d7-db60ef21e9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mô hình Blind box Gấu bông Baby Three Lucky Cat Zipper Bag Series ( Mèo Thần Tài ) BABY THREE</value>
      <webElementGuid>45e65914-03fa-445d-9d85-9346394a8e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/ind-box-gau-bong-baby-three-lucky-cat-zipper-bag-series-baby-three__1__4d2c63bc12cf47b6a6ee78f0d6d4efd7_large.jpg</value>
      <webElementGuid>546d04a2-1fd8-4850-b116-8f2c98a4ffdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>cfda32c1-5dbd-4665-8778-94b30a53e13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>1054de86-670d-4e44-9d54-8efdecd56eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/ind-box-gau-bong-baby-three-lucky-cat-zipper-bag-series-baby-three__1__4d2c63bc12cf47b6a6ee78f0d6d4efd7_large.jpg</value>
      <webElementGuid>247f4bdd-de0e-4ada-9f4e-9b48f0ef653b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-body&quot;)/div[@class=&quot;col-sm-8 col-xs-12&quot;]/div[@class=&quot;row filter-here&quot;]/div[@class=&quot;content-product-list collection-list clearfix&quot;]/div[@class=&quot;pro-loop animation-tran&quot;]/div[@class=&quot;product-block  pro-new&quot;]/div[@class=&quot;product-img img-eff&quot;]/a[@class=&quot;image-resize&quot;]/img[@class=&quot;img-loop image-product-loop bigloaded&quot;]</value>
      <webElementGuid>d3d482f6-5d10-48c6-94b1-a975123ece6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div[3]/div/div/a/img</value>
      <webElementGuid>f6008c2d-3fde-449f-843f-966c92fbdf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mô hình Blind box Gấu bông Baby Three Lucky Cat Zipper Bag Series ( Mèo Thần Tài ) BABY THREE']</value>
      <webElementGuid>816bf877-6faa-422c-a442-5cf778342633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/img</value>
      <webElementGuid>d8a4ce59-b6d2-4a82-855f-0c445b02cd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Mô hình Blind box Gấu bông Baby Three Lucky Cat Zipper Bag Series ( Mèo Thần Tài ) BABY THREE' and @src = '//product.hstatic.net/200000726533/product/ind-box-gau-bong-baby-three-lucky-cat-zipper-bag-series-baby-three__1__4d2c63bc12cf47b6a6ee78f0d6d4efd7_large.jpg']</value>
      <webElementGuid>8cb229cf-e6d6-4091-9778-d8ade2843491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div[2]/div/div/a/img</value>
      <webElementGuid>12fcdabc-9ba4-4c2f-a381-bb5ba87fbe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mô hình Blind box Gấu bông Take Me Out Zipper Bag BABY THREE']</value>
      <webElementGuid>befba72d-4269-4d8e-b7d9-ba79d036f56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/a/img</value>
      <webElementGuid>13bd6da3-b231-4e80-b577-c98a0a7c195d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Mô hình Blind box Gấu bông Take Me Out Zipper Bag BABY THREE' and @src = '//product.hstatic.net/200000726533/product/mo-hinh-blind-box-gau-bong-take-me-out-zipper-bag-baby-three__1__8b6fca2e10fb454380992863f411bdc6_large.jpg']</value>
      <webElementGuid>3a5ecc6b-1ed7-44c4-b2cb-7cc07aae8002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
