<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thanh ton_site-close-handle</name>
   <tag></tag>
   <elementGuidId>7bb02714-97bc-4391-b818-7006d836765f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#site-close-handle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='site-close-handle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9542de77-6cf6-4ecf-a3b1-3b85e976506a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>site-close-handle</value>
      <webElementGuid>56d19762-b539-4291-8086-ef37c4d34394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-close-handle</value>
      <webElementGuid>b51b122d-60a9-433d-a7ae-c49355b5d649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>bc34a1e1-acfa-4ee9-b605-44026a1465c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>19aeb6fb-6bcd-49f8-b007-fe6b0c154fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-close-handle&quot;)</value>
      <webElementGuid>23fcdb80-2be0-4902-83f7-3f8399aec96b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='site-close-handle']</value>
      <webElementGuid>44cba093-7abc-470a-a7de-7fd04c0f7d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-nav--mobile']/button</value>
      <webElementGuid>8951bb03-05c2-4844-8501-e0ee014030bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh toán'])[2]/following::button[1]</value>
      <webElementGuid>c32e6c36-61f8-4b70-b85e-354d790c6568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem giỏ hàng'])[1]/following::button[1]</value>
      <webElementGuid>e30d171d-cfc8-4fe9-b046-b3d187264c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/preceding::button[1]</value>
      <webElementGuid>49517c12-d598-49cb-87ba-da6dbf88ca1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông Báo'])[1]/preceding::button[2]</value>
      <webElementGuid>cc6a783e-91e0-4c7a-a0a8-967e0e26bce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>953526c6-cee7-4333-a395-35c49e8dbcf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'site-close-handle' and @title = 'Đóng']</value>
      <webElementGuid>0b31c251-e7c3-4ef9-93a1-54a4ff5920b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
