<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Black</name>
   <tag></tag>
   <elementGuidId>45ce9eda-bb7f-447f-8f18-12f4c3289364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#het-hang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='het-hang']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>63418a97-9b30-4dfb-9984-272925745e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/products/mo-hinh-xe-mitsubishi-outlander-2021-1-64-jkm?color=Black</value>
      <webElementGuid>0004e487-7530-43de-8754-3b560a8003c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>het-hang</value>
      <webElementGuid>9d034912-d408-449c-8a64-f168ff485385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handle</name>
      <type>Main</type>
      <value>black</value>
      <webElementGuid>03f6f24c-5990-4673-bf69-443881e0c927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>het-hang  black</value>
      <webElementGuid>bc93d086-de79-4ded-897c-d9f08099ff91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>swatch-0-black</value>
      <webElementGuid>f0c9a14b-c7a7-4b58-9529-2b531fd61eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Black
			</value>
      <webElementGuid>a3f4645e-6c32-4193-8768-0a76fa2bf8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;het-hang&quot;)</value>
      <webElementGuid>2727cacc-f9cc-4518-9b97-49f8159c808f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='het-hang']</value>
      <webElementGuid>f5c94a88-89d7-4596-9a76-6766d3ba882b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='variant-swatch-0']/div[2]/div[2]/label</value>
      <webElementGuid>64524df6-93fb-45ea-b11d-2d6f766b3607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='White'])[2]/following::label[1]</value>
      <webElementGuid>1276de36-63cd-4047-a9b0-200b2bd75686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn màu:'])[1]/following::label[2]</value>
      <webElementGuid>e90150b0-cbf0-455c-a3b0-308466640d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>d8e7f6a7-2113-4042-af7d-7551a234658f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'het-hang' and (text() = '
				Black
			' or . = '
				Black
			')]</value>
      <webElementGuid>6fce5989-8c6a-4e8b-874d-b3284e47d757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
