<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S in thoi_addressaddress2</name>
   <tag></tag>
   <elementGuidId>a99cea7f-7553-4f3f-afd5-9864904ae954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_address2_10209597660</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_address2_10209597660']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3293a073-e5a9-441b-b8f9-8a2ff3ac482c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>abb1d4f8-15dc-44ab-85fa-a7be590a8417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_address2_10209597660</value>
      <webElementGuid>17521a54-1682-46a7-b49d-b32504efbafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textbox</value>
      <webElementGuid>edb534e9-7176-42c8-8fac-3413c0dc932f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[address2]</value>
      <webElementGuid>90e24e2e-5855-4eca-9a2b-ab07c0707897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d0118aa1-484a-4c0f-8613-4d65d1199161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ 2</value>
      <webElementGuid>48aecd54-10f4-4fe3-8969-d15a6caff404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_address2_10209597660&quot;)</value>
      <webElementGuid>d752b574-8fd8-45b2-88a8-58a5cbc8b8e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_address2_10209597660']</value>
      <webElementGuid>932975ea-549a-42f7-b9c3-3ef1410249da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address_form_10209597660']/div[5]/input</value>
      <webElementGuid>a934817b-09cf-49d7-a3dc-233799524b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>ce5e360f-24bc-45ce-92c1-5fd4cc9c1e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address_address2_10209597660' and @name = 'address[address2]' and @placeholder = 'Địa chỉ 2']</value>
      <webElementGuid>c247b504-9af9-4b82-84d8-088073f07b7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
