<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S in thoi_addresslast_name</name>
   <tag></tag>
   <elementGuidId>b16f51ab-9201-4942-8487-e037a66500ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_last_name_10209597660</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_last_name_10209597660']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61c7026f-4c57-4a58-9ab3-9c47faae0eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54835dfb-4dae-4615-bd8c-59ddb8bc97d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_last_name_10209597660</value>
      <webElementGuid>d60fa592-d2fb-464f-9ec3-629257e27abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textbox</value>
      <webElementGuid>08e7646e-f950-4094-999a-fa06a1db7150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[last_name]</value>
      <webElementGuid>cc01ead8-a5c6-4116-9e49-4f304aa5fe56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>987f6893-728d-4e1a-ab5a-ee32b5d5ed66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Phạm</value>
      <webElementGuid>210ad1f9-07f9-4b87-b25f-cb04bdf7d7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Họ</value>
      <webElementGuid>7dedbb21-d6e3-4968-b209-75d84c69b10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_last_name_10209597660&quot;)</value>
      <webElementGuid>ac2aee67-5419-46e5-b069-a313f6f5f9a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_last_name_10209597660']</value>
      <webElementGuid>f10ed484-9285-4152-bf22-d4c6e767580b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address_form_10209597660']/div/input</value>
      <webElementGuid>b2f342c8-b662-4428-8877-112bcc0b5cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/input</value>
      <webElementGuid>7ed3f1cb-0451-4623-a6fa-f1e00e30b9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address_last_name_10209597660' and @name = 'address[last_name]' and @placeholder = 'Họ']</value>
      <webElementGuid>d64f865d-8719-4ec6-8f12-8e9798f17ea9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
