<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_t lm a ch mc nh_addressdefault</name>
   <tag></tag>
   <elementGuidId>a575848b-d0ef-4573-be23-4ca8e121f003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_default_address_10209597660</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_default_address_10209597660']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5d06111-b583-48b0-ae25-68f808fb40e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>76e99b9b-8547-4a65-b8db-bfe18b0f5785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_default_address_10209597660</value>
      <webElementGuid>7f3d5eaa-347d-4554-b2ad-23e8dc16b36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[default]</value>
      <webElementGuid>209df7b0-3841-4fbb-bf00-7c41bda53c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0c63afc9-9c39-4920-8b42-8a95620782e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_default_address_10209597660&quot;)</value>
      <webElementGuid>8758e498-6b8b-4600-b63c-e0bce8318bed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_default_address_10209597660']</value>
      <webElementGuid>72ef214e-3668-42b0-a6e3-a05adebe83b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address_form_10209597660']/div[10]/input</value>
      <webElementGuid>7be10687-8cd8-4b2f-9024-b210f8124b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>df0e84fe-725f-4137-a0e1-31b2906a4d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'address_default_address_10209597660' and @name = 'address[default]']</value>
      <webElementGuid>ba06f71f-54f4-465b-acc9-34aaf755aea1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
