<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S in thoi_addressaddress1</name>
   <tag></tag>
   <elementGuidId>214db799-e70f-493e-bfdf-aa53e792b757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_address1_10209597660</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_address1_10209597660']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>331b5a17-f33b-4238-a567-25bcc2bfeb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4cb3bb7-be68-45f2-b14d-71ec90b08e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_address1_10209597660</value>
      <webElementGuid>920eec67-346e-4430-8d58-df2a3923814b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textbox</value>
      <webElementGuid>c50d2cf3-0332-4f0d-96e7-baca3c882139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[address1]</value>
      <webElementGuid>6cf2b82b-5b01-4966-982a-a9fc3af8cb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>aedde75e-2fd6-4ab6-ae00-e5dc07084420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ 1</value>
      <webElementGuid>2f3e4401-8a39-40ea-b483-6504f508d128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_address1_10209597660&quot;)</value>
      <webElementGuid>2b2e25ed-a12b-4f93-a957-92acb5170073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_address1_10209597660']</value>
      <webElementGuid>cad060cb-c8d4-46bb-9c67-95c20b894202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address_form_10209597660']/div[4]/input</value>
      <webElementGuid>58bb39f0-d94c-4033-b4d2-d2407cff4729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>64df2c15-9833-4f38-8fca-278b246cb9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address_address1_10209597660' and @name = 'address[address1]' and @placeholder = 'Địa chỉ 1']</value>
      <webElementGuid>218d74e7-2160-4287-99c0-6966bd9fed82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
