<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S in thoi_addressphone</name>
   <tag></tag>
   <elementGuidId>5aa3609f-f09c-4a60-93af-3c44d6fad3ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_phone_10209597660</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_phone_10209597660']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>054c1f11-8384-4701-88fd-fbb6d92f02b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e7c8ab2-6e6a-4f02-9125-4807e653a043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_phone_10209597660</value>
      <webElementGuid>74917c05-a890-470c-9e9b-c23762d5c85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textbox</value>
      <webElementGuid>24c155eb-0a61-4ef7-a83f-4b437f186778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[phone]</value>
      <webElementGuid>6fcd3475-33c4-4883-b964-89de73f820c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>567473b0-7811-41ee-8311-5f792e18fa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Số điện thoại</value>
      <webElementGuid>b22494fa-1186-4534-a1ae-73b62bed33d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_phone_10209597660&quot;)</value>
      <webElementGuid>e7365a5a-1e44-4bc1-bcdc-c5e0f058b9ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_phone_10209597660']</value>
      <webElementGuid>7f35ea15-7248-4e28-a26d-765567266654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address_form_10209597660']/div[9]/input</value>
      <webElementGuid>ebe0eb0d-3af0-449d-9ada-bb18fd1be6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>a1c8ab70-f952-4565-8a68-03f03b24ab36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address_phone_10209597660' and @name = 'address[phone]' and @placeholder = 'Số điện thoại']</value>
      <webElementGuid>cade4785-6ba9-450f-8d29-6ab4582dc245</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
