<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_H Ch MinhH Ni NngAn GiangB Ra - Vng _687e44</name>
   <tag></tag>
   <elementGuidId>14c67019-38c1-4cc0-9970-4562d1ba3af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_province_10209597660</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='address_province_10209597660']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b3913bce-41b3-4bcb-8906-df3c394224a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_province_10209597660</value>
      <webElementGuid>e3d2d03c-6102-44b4-b301-b0948dab3b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>daf4b10d-0a06-44af-9d08-9174f40b3a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[province]</value>
      <webElementGuid>9f636537-22b4-4a13-b1fa-5ba11e9e1b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-default</name>
      <type>Main</type>
      <value>Hồ Chí Minh</value>
      <webElementGuid>872d7048-820d-4db4-bfbf-47cd11312074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hồ Chí MinhHà NộiĐà NẵngAn GiangBà Rịa - Vũng TàuBình DươngBình PhướcBình ThuậnBình ĐịnhBạc LiêuBắc GiangBắc KạnBắc NinhBến TreCao BằngCà MauCần ThơGia LaiHà GiangHà NamHà TĩnhHòa BìnhHưng YênHải DươngHải PhòngHậu GiangKhánh HòaKiên GiangKon TumLai ChâuLong AnLào CaiLâm ĐồngLạng SơnNam ĐịnhNghệ AnNinh BìnhNinh ThuậnPhú ThọPhú YênQuảng BìnhQuảng NamQuảng NgãiQuảng NinhQuảng TrịSóc TrăngSơn LaThanh HóaThái BìnhThái NguyênThừa Thiên HuếTiền GiangTrà VinhTuyên QuangTây NinhVĩnh LongVĩnh PhúcYên BáiĐiện BiênĐắk LắkĐắk NôngĐồng NaiĐồng Tháp</value>
      <webElementGuid>b52f16e6-3fe1-42d4-83c4-356ca185adfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_province_10209597660&quot;)</value>
      <webElementGuid>0b56b71a-c780-48ed-a19d-db90e0881757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='address_province_10209597660']</value>
      <webElementGuid>22dfe3a9-4887-40c1-abed-17d3c99d22d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address_province_container_10209597660']/select</value>
      <webElementGuid>a2903540-eefc-44fa-8aa6-8916e0e1658e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số điện thoại:'])[1]/following::select[2]</value>
      <webElementGuid>0c8e052f-6df8-438b-b829-e01dbfbf6eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ:'])[1]/following::select[2]</value>
      <webElementGuid>590bae16-aba9-4004-849b-c2692316e503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>decb4d92-c022-465f-a5cc-c4f7f05fb179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'address_province_10209597660' and @name = 'address[province]' and (text() = 'Hồ Chí MinhHà NộiĐà NẵngAn GiangBà Rịa - Vũng TàuBình DươngBình PhướcBình ThuậnBình ĐịnhBạc LiêuBắc GiangBắc KạnBắc NinhBến TreCao BằngCà MauCần ThơGia LaiHà GiangHà NamHà TĩnhHòa BìnhHưng YênHải DươngHải PhòngHậu GiangKhánh HòaKiên GiangKon TumLai ChâuLong AnLào CaiLâm ĐồngLạng SơnNam ĐịnhNghệ AnNinh BìnhNinh ThuậnPhú ThọPhú YênQuảng BìnhQuảng NamQuảng NgãiQuảng NinhQuảng TrịSóc TrăngSơn LaThanh HóaThái BìnhThái NguyênThừa Thiên HuếTiền GiangTrà VinhTuyên QuangTây NinhVĩnh LongVĩnh PhúcYên BáiĐiện BiênĐắk LắkĐắk NôngĐồng NaiĐồng Tháp' or . = 'Hồ Chí MinhHà NộiĐà NẵngAn GiangBà Rịa - Vũng TàuBình DươngBình PhướcBình ThuậnBình ĐịnhBạc LiêuBắc GiangBắc KạnBắc NinhBến TreCao BằngCà MauCần ThơGia LaiHà GiangHà NamHà TĩnhHòa BìnhHưng YênHải DươngHải PhòngHậu GiangKhánh HòaKiên GiangKon TumLai ChâuLong AnLào CaiLâm ĐồngLạng SơnNam ĐịnhNghệ AnNinh BìnhNinh ThuậnPhú ThọPhú YênQuảng BìnhQuảng NamQuảng NgãiQuảng NinhQuảng TrịSóc TrăngSơn LaThanh HóaThái BìnhThái NguyênThừa Thiên HuếTiền GiangTrà VinhTuyên QuangTây NinhVĩnh LongVĩnh PhúcYên BáiĐiện BiênĐắk LắkĐắk NôngĐồng NaiĐồng Tháp')]</value>
      <webElementGuid>5fecf3ab-f005-4582-9a99-0dce0cfa5c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
