<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thanh ton_site-close-handle</name>
   <tag></tag>
   <elementGuidId>7a3392c6-ed26-4150-845e-2b5ce92a9988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#site-close-handle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='site-close-handle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d238d5b6-026c-4b44-b739-4bb1950c51f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>site-close-handle</value>
      <webElementGuid>a5f7e7a6-1908-4e12-9d56-c8a7e22838f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-close-handle</value>
      <webElementGuid>51d17b2d-afc8-4d60-84b2-3da7be86a50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>54a3239a-7cf3-4bb3-a39c-62cc07d87700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>47fe9f5e-a963-46b3-91e1-8c3f0360dbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-close-handle&quot;)</value>
      <webElementGuid>f0d79859-a8d2-4ab6-9527-ab93bb693184</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='site-close-handle']</value>
      <webElementGuid>d6b42066-92ce-4fe3-a114-c8f173059153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-nav--mobile']/button</value>
      <webElementGuid>9ae2f693-47c7-4968-981a-f1b7d266610d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh toán'])[2]/following::button[1]</value>
      <webElementGuid>31c4e463-d879-44b6-9296-32aa0705b115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem giỏ hàng'])[1]/following::button[1]</value>
      <webElementGuid>2f2496c0-e89f-4cad-a9d6-7897b068b5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/preceding::button[1]</value>
      <webElementGuid>f84efcd1-513f-4b08-b0f2-b18459252479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông Báo'])[1]/preceding::button[2]</value>
      <webElementGuid>47e9b1c1-005c-4eb6-8996-ff7a977d76a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>4d14b3af-6328-425f-abf8-8035c6031c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'site-close-handle' and @title = 'Đóng']</value>
      <webElementGuid>14e54e76-e426-4e12-9663-ce43774c06d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
