<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_M hnh xe Mitsubishi Outlander 2021 164 JKM249,000XEM THM</name>
   <tag></tag>
   <elementGuidId>74fd9c63-f552-45b1-9f7b-0a124fc414f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#splide01-slide03</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='splide01-slide03']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ce89b182-b745-435a-b83a-523a3c34bc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>splide__slide is-visible</value>
      <webElementGuid>1daf5141-ef41-4530-a845-bf50f9101469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>splide01-slide03</value>
      <webElementGuid>3323c277-47e6-4ed5-9a9f-7aa25ff3451f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>group</value>
      <webElementGuid>286b0ead-76c9-4e2d-b0c4-3a46287294c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>slide</value>
      <webElementGuid>e7b017b0-955e-4b54-821f-f48bc697017d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>3 of 10</value>
      <webElementGuid>4e7c6fbf-ae62-4ed3-88e0-ef8e803cf755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mô hình xe Mitsubishi Outlander 2021 1:64 JKM249,000₫XEM THÊM</value>
      <webElementGuid>bd0ca5d7-e66f-4bf8-a18b-14bf80694b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide01-slide03&quot;)</value>
      <webElementGuid>4a1b6dbf-9216-4bc8-bac5-433721a4db17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_M hnh xe Nissan Skyline GT-R R34 V-Spe_ed949f/iframe_Cha c nh gi no_Lhk89RW2_y0KGlpI</value>
      <webElementGuid>c2601198-4515-475a-aa22-8202d77e8642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='splide01-slide03']</value>
      <webElementGuid>6d98061e-43cb-4394-8ff4-54b721160600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='splide01-list']/li[11]</value>
      <webElementGuid>0b7e31f2-a585-4f5e-a61f-cb80f06239c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XEM THÊM'])[10]/following::li[1]</value>
      <webElementGuid>5d1a84d4-62fb-4bcc-a45a-096d46694054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô hình xe Porsche 356B 1:36 KINSMART'])[1]/following::li[1]</value>
      <webElementGuid>cf6078ce-c1ff-49cb-b461-c7b19e6922a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]</value>
      <webElementGuid>f865b167-105b-4607-ad35-07198d25ab0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'splide01-slide03' and (text() = 'Mô hình xe Mitsubishi Outlander 2021 1:64 JKM249,000₫XEM THÊM' or . = 'Mô hình xe Mitsubishi Outlander 2021 1:64 JKM249,000₫XEM THÊM')]</value>
      <webElementGuid>4f5d7177-3ecb-4de8-b0cb-de012f8353c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
