<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cu hi thng gp (0)</name>
   <tag></tag>
   <elementGuidId>b3a000cf-00e2-44d6-8ac4-6692675cbcd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8939101-a9f8-43b6-8b16-50929fa679e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4a3aaa4-739a-454a-9b59-ea0364259af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onirvapp-tab-btn</value>
      <webElementGuid>0035335b-a8c5-4e8b-b859-c7eaba3c7268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Câu hỏi thường gặp (0)</value>
      <webElementGuid>aa8467bc-05df-4a75-9d90-ef4e71a778a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onirvapp-detail-body&quot;)/div[@class=&quot;onirvapp-detail-tabs&quot;]/div[@class=&quot;onirvapp-tab&quot;]/button[@class=&quot;onirvapp-tab-btn&quot;]</value>
      <webElementGuid>3f01b4d4-5b90-454f-b2e6-e36a95d95bca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>31cc65c8-1238-42c0-b897-3687b3e067ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onirvapp-detail-body']/div/div/button[2]</value>
      <webElementGuid>3be34217-7ca8-4625-b692-0b73d5b5a585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lượt thích'])[1]/following::button[7]</value>
      <webElementGuid>70a09fa0-1f3c-4a8d-9fa2-8c77513f9c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT'])[1]/preceding::button[2]</value>
      <webElementGuid>6a888474-8122-44cd-bd76-bfaf34148868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Câu hỏi thường gặp']/parent::*</value>
      <webElementGuid>a32bb049-bc3e-4906-b2e5-b98043e49763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>61408db2-ab50-41fa-8de2-5800d20ba917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Câu hỏi thường gặp (0)' or . = 'Câu hỏi thường gặp (0)')]</value>
      <webElementGuid>b232b7ef-f14c-405f-9d89-812598bb29fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
