<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Nhp link youtube, VD httpswww.youtub_cc33ba</name>
   <tag></tag>
   <elementGuidId>90aaeb24-349c-479f-ae10-aa83eb072cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;youtube&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='youtube']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>431b4fb0-042a-4938-a4ea-13b6d7cd6b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>974878f1-eeed-4c88-ad2f-317cafee33f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>youtube</value>
      <webElementGuid>0ab371c5-7298-4075-822e-d9d932dfc7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onirvapp-form-input</value>
      <webElementGuid>5e6126d1-a3d6-4478-85e6-351c12d27cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:r1:&quot;)/form[1]/div[@class=&quot;onirvapp-form-container&quot;]/div[@class=&quot;onirvapp-form-content&quot;]/div[@class=&quot;onirvapp-form-group&quot;]/input[@class=&quot;onirvapp-form-input&quot;]</value>
      <webElementGuid>39fdca20-feb2-4c10-b52c-eb413b2b6a42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='youtube']</value>
      <webElementGuid>439485b4-d488-425e-9054-75075822a87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:r1:']/form/div/div/div[7]/input</value>
      <webElementGuid>3a95764d-0677-4fe3-9c76-4efbce74dfd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>eee1aedf-23f1-472d-a721-cac97f997513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'youtube']</value>
      <webElementGuid>9c4d7a0f-44dc-41da-b5cf-4b071438d586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
