<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Ti ln</name>
   <tag></tag>
   <elementGuidId>bf90556b-8a87-4743-9645-547eb63bc3e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.onirvapp-images-withupload-action-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-panel-:r1:']/form/div/div/div[8]/div/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bb1cf984-9ff3-4c82-9cb4-a5a7c215eaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cm5kccqab0006359xrnks9629</value>
      <webElementGuid>b972f8fd-0c49-44e8-84a8-8affd85c54e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onirvapp-images-withupload-action-label</value>
      <webElementGuid>706ff342-41dd-4e30-81a2-16d770079885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tải lên</value>
      <webElementGuid>ae5f6170-8a79-43ed-bbd1-fa987c1f7bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:r1:&quot;)/form[1]/div[@class=&quot;onirvapp-form-container&quot;]/div[@class=&quot;onirvapp-form-content&quot;]/div[@class=&quot;onirvapp-form-group&quot;]/div[@class=&quot;onirvapp-form-images&quot;]/div[@class=&quot;onirvapp-images-withupload&quot;]/div[@class=&quot;onirvapp-images-withupload-action&quot;]/label[@class=&quot;onirvapp-images-withupload-action-label&quot;]</value>
      <webElementGuid>06a5351b-7bba-4c6e-885a-8d0c735dffc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:r1:']/form/div/div/div[8]/div/div/div[2]/label</value>
      <webElementGuid>1182b49a-7f14-4dbb-8cb7-0c8143ad2446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Tối đa 5 hình, mỗi hình không quá 5mb)'])[1]/following::label[1]</value>
      <webElementGuid>d6c401f9-c29b-4211-ad70-928f515a86d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hủy'])[1]/preceding::label[1]</value>
      <webElementGuid>c6a5b52b-9214-4ffb-b2d5-0fcd074f1607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/label</value>
      <webElementGuid>c019566f-dfc1-43b1-8e84-3faee6fa666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Tải lên' or . = 'Tải lên')]</value>
      <webElementGuid>839dc612-f77e-44bf-93ce-7ab4e2a21936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
