<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_M hnh Blind box Mc kha Gu bng Baby Three Romantic Ocean ( i Dng Lng Mn ) BABY THREE279,000XEM THM</name>
   <tag></tag>
   <elementGuidId>8ec2d467-0529-4455-a727-09becef2c4f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#splide01-slide03</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='splide01-slide03']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>91ef1a59-3161-4731-8c96-ed3f91cecec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>splide__slide is-visible</value>
      <webElementGuid>71cbe794-a562-43c3-8333-9402b1a41faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>splide01-slide03</value>
      <webElementGuid>647c400e-3e58-4da1-80ea-3accabc2ffc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>group</value>
      <webElementGuid>0d5d8fec-8195-4277-845e-03e2b95eb487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>slide</value>
      <webElementGuid>b35930e1-63c4-4e49-842a-61228c7e39bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>3 of 10</value>
      <webElementGuid>2bf892ae-ef8d-4931-a944-10b9a3e15627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mô hình Blind box Móc khóa Gấu bông Baby Three Romantic Ocean ( Đại Dương Lãng Mạn ) BABY THREE279,000₫XEM THÊM</value>
      <webElementGuid>bca4a3f5-1d56-46a6-850b-ec0f9f89b6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide01-slide03&quot;)</value>
      <webElementGuid>fc30f606-5882-4d32-b953-18dd45816c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_M hnh Blind box Mc kha Gu bng Baby Thr_53e30d/iframe_Bnh lun_sZK9YV1o3IVZlUsy</value>
      <webElementGuid>89d89228-1772-4a9a-ac6a-55fcd0e2dedb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='splide01-slide03']</value>
      <webElementGuid>96aac237-20b8-4f24-82a5-e83f7d943ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='splide01-list']/li[11]</value>
      <webElementGuid>fd3f1c08-abb8-4885-b43c-2506d8df66c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XEM THÊM'])[10]/following::li[1]</value>
      <webElementGuid>6d0d652f-5a3b-4ee1-b5e2-09419e5c86df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô hình Blind box Gấu bông Baby Three 12 Chinese Zodiac ( 12 Con Giáp ) BABY THREE'])[1]/following::li[1]</value>
      <webElementGuid>965b72a1-9064-4473-a750-363391a55628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]</value>
      <webElementGuid>9074ae59-05d2-4dc7-b525-075159ddb0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'splide01-slide03' and (text() = 'Mô hình Blind box Móc khóa Gấu bông Baby Three Romantic Ocean ( Đại Dương Lãng Mạn ) BABY THREE279,000₫XEM THÊM' or . = 'Mô hình Blind box Móc khóa Gấu bông Baby Three Romantic Ocean ( Đại Dương Lãng Mạn ) BABY THREE279,000₫XEM THÊM')]</value>
      <webElementGuid>57576294-dff8-4e6d-b0a8-e691b47b433f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
