<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ti ln</name>
   <tag></tag>
   <elementGuidId>b84c8f4c-8dbe-4d75-b321-b368095d9a2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.onirvapp-images-withupload-action-labeltext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-panel-:r1:']/form/div/div/div[8]/div/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8d9603a1-d0ba-462b-9229-427bbc8a9dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onirvapp-images-withupload-action-labeltext</value>
      <webElementGuid>101f53ba-394b-44dc-9dfa-fc6b681ae39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tải lên</value>
      <webElementGuid>dc560514-5c31-4073-8d42-8614919f80b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:r1:&quot;)/form[1]/div[@class=&quot;onirvapp-form-container&quot;]/div[@class=&quot;onirvapp-form-content&quot;]/div[@class=&quot;onirvapp-form-group&quot;]/div[@class=&quot;onirvapp-form-images&quot;]/div[@class=&quot;onirvapp-images-withupload&quot;]/div[@class=&quot;onirvapp-images-withupload-action&quot;]/label[@class=&quot;onirvapp-images-withupload-action-label&quot;]/span[@class=&quot;onirvapp-images-withupload-action-labeltext&quot;]</value>
      <webElementGuid>1105333a-6a8f-4d5b-8903-8bd7d8377a26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:r1:']/form/div/div/div[8]/div/div/div/label/span</value>
      <webElementGuid>8e90b5df-8172-493b-b60f-40b4951a6e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Tối đa 5 hình, mỗi hình không quá 5mb)'])[1]/following::span[1]</value>
      <webElementGuid>18b0e7b3-453e-4902-9b18-04139fc72fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hủy'])[1]/preceding::span[1]</value>
      <webElementGuid>3cb66e1a-4acc-4041-94d2-8fa2dfb4801c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gửi đánh giá'])[1]/preceding::span[1]</value>
      <webElementGuid>0881555b-acdf-4060-9ea7-0344f15da3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tải lên']/parent::*</value>
      <webElementGuid>f17511e8-1168-4345-a8b9-466635ca677a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/label/span</value>
      <webElementGuid>0dca3619-ebac-4fdf-a355-092fca71cb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tải lên' or . = 'Tải lên')]</value>
      <webElementGuid>a114832f-db64-46e9-a8a9-18d7e1a0fe3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
