<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_1</name>
   <tag></tag>
   <elementGuidId>0a61f71f-3745-4ba5-9301-2068c5527aa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.onirvapp-btn.onirvapp-btn-icon.onirvapp-btn-close > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Gửi đánh giá thành công'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>7b0f7e80-c516-4a93-b5c2-0160a4fd8066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>c4b13c95-b5cd-4b52-a755-a269852cc0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>0a8c1c2c-cf2a-43cc-9eb6-704117101ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>e18acd00-27f2-42f2-9e48-a181e5004b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b2a5a3b3-dd3e-4474-87a0-c7c6e1f2aac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>f151847c-95d0-43ca-92f8-4587a6b9db53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a3751a6-1a86-4a85-b473-a8249a451349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:r1:&quot;)/button[@class=&quot;onirvapp-btn onirvapp-btn-icon onirvapp-btn-close&quot;]/svg[1]</value>
      <webElementGuid>d42b66d7-57a1-4be7-beb8-5cca9971de12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gửi đánh giá thành công'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d69ae447-cb17-4640-97b5-3af5cf7a2217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đóng'])[2]/following::*[name()='svg'][2]</value>
      <webElementGuid>d356ee45-9c83-4f79-9b52-39d5082f3264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viết đánh giá mới'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>68ef667c-7e03-4735-98fb-7907a4e662f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
