<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cp nht thng tin</name>
   <tag></tag>
   <elementGuidId>7fb650a9-c308-4298-b814-5d7b9dcb823b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#view_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='view_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ab22b60-5dc3-43ed-9535-1d5df4104481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view_address</value>
      <webElementGuid>26424b00-7895-4a10-bd58-41073e012592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/addresses</value>
      <webElementGuid>cb014d37-f432-404e-8a09-c72a3b33bbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cập nhật thông tin</value>
      <webElementGuid>3786c441-b191-40fc-b98e-5f814d1e451d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_address&quot;)</value>
      <webElementGuid>f9616910-b1d9-4692-afeb-92a0d6db13d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='view_address']</value>
      <webElementGuid>1b67eafa-7632-4640-abce-2483a180ed90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_sidebar']/div/a</value>
      <webElementGuid>937f57d7-f456-4f39-802e-1c0b0afabb7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cập nhật thông tin')]</value>
      <webElementGuid>6842cf63-8690-4ec5-b6f8-4bac081bc7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Điện thoại:'])[1]/following::a[1]</value>
      <webElementGuid>16d317b8-a516-44f2-88a4-dae3c40022d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tỉnh/Thành phố:'])[1]/following::a[1]</value>
      <webElementGuid>db35d458-4f7b-44f9-85f8-06b8b127ed15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOCIAL'])[1]/preceding::a[1]</value>
      <webElementGuid>0173a52d-b9e9-4ab5-8d8d-058ecb54f205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đối Tác'])[1]/preceding::a[5]</value>
      <webElementGuid>2abf9a0f-4978-4ff2-b2a5-4fca55506b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cập nhật thông tin']/parent::*</value>
      <webElementGuid>0d664d21-8502-4c83-8939-e88990fa830a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/account/addresses')])[2]</value>
      <webElementGuid>6a7db0ad-d6c9-49af-95b7-18baf3e6b98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a</value>
      <webElementGuid>497b0282-88e7-433c-9fa2-2b5766920286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'view_address' and @href = '/account/addresses' and (text() = 'Cập nhật thông tin' or . = 'Cập nhật thông tin')]</value>
      <webElementGuid>a4a64b08-0e6d-4736-8d11-a6a638cf401b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
