<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thm vo gi</name>
   <tag></tag>
   <elementGuidId>47ae0fba-39e7-42d8-95e5-f0e571736b01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68e22486-1857-473d-b415-4038b6dc949e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>19d8581c-396f-4a77-9670-2c0a0387fa2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy now</value>
      <webElementGuid>265f288d-6e32-487b-842e-28feee5c4e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>35ad21f5-dbbc-4dea-bcee-e0ae0653e145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>buy_now('1142867668')</value>
      <webElementGuid>2dbeadaf-8b1f-4e01-b552-ad2d01c4c2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm vào giỏ</value>
      <webElementGuid>c0468c0d-0672-4a60-be8b-0cada0096a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-body&quot;)/div[@class=&quot;col-sm-8 col-xs-12&quot;]/div[@class=&quot;row filter-here&quot;]/div[@class=&quot;content-product-list collection-list clearfix&quot;]/div[@class=&quot;pro-loop animation-tran active&quot;]/div[@class=&quot;product-block  pro-new&quot;]/div[@class=&quot;product-detail clearfix&quot;]/div[@class=&quot;quick-action&quot;]/div[@class=&quot;button-add&quot;]/button[@class=&quot;action&quot;]</value>
      <webElementGuid>e9df1c29-bd90-4c59-8e65-084a6ee8aa3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>9d3e3c49-1fec-4a7c-a718-8196018d0990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>b181c81c-29df-4b6c-89f5-0049b1ff14cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô hình xe Bugatti Mistral 1:18 BBURAGO'])[1]/following::button[1]</value>
      <webElementGuid>02a6becc-bcce-4489-9e77-81298e4f441d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiêu đề Z-A'])[1]/following::button[1]</value>
      <webElementGuid>3f49be84-61ad-4956-89c9-01dfc0752da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô hình xe Nissan Skyline GT-R R34 V-Spec 1:64 MiniGT'])[1]/preceding::button[1]</value>
      <webElementGuid>9440d189-0404-4066-afd5-ee60e3ed2b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm vào giỏ'])[2]/preceding::button[1]</value>
      <webElementGuid>83c32e0e-a0e5-4448-b6a1-b7ffd60a191e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thêm vào giỏ']/parent::*</value>
      <webElementGuid>a06dd5d9-b561-4639-b7df-11fa246b2388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>51237b4e-42e5-4595-b1f2-d7c350bc6327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @title = 'Buy now' and (text() = 'Thêm vào giỏ' or . = 'Thêm vào giỏ')]</value>
      <webElementGuid>8b440ead-67c8-4c6e-b359-ea64b239e920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
