<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thm vo gi_1</name>
   <tag></tag>
   <elementGuidId>620afc70-28a0-454e-a72e-18720f40d842</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a7fb731-9c60-4bda-a285-fc8794c9422a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>12ede5f0-fd7f-4878-9850-aa513e7ffe96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy now</value>
      <webElementGuid>c0289567-0b32-4d31-97eb-60b721cf6f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>cc3667ed-c291-4f55-b3a2-dd50b34b7f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>buy_now('1142613695')</value>
      <webElementGuid>2ac0fcd9-36b4-4f06-938a-fe06c23a3be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm vào giỏ</value>
      <webElementGuid>4395b7fc-01dd-463f-8cfb-4a4460b486f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-body&quot;)/div[@class=&quot;col-sm-8 col-xs-12&quot;]/div[@class=&quot;row filter-here&quot;]/div[@class=&quot;content-product-list collection-list clearfix&quot;]/div[@class=&quot;pro-loop animation-tran active&quot;]/div[@class=&quot;product-block  pro-new&quot;]/div[@class=&quot;product-detail clearfix&quot;]/div[@class=&quot;quick-action&quot;]/div[@class=&quot;button-add&quot;]/button[@class=&quot;action&quot;]</value>
      <webElementGuid>03eaf8ee-6d23-4cb7-aa78-89c13002dacb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[4]</value>
      <webElementGuid>26388728-cff4-449d-8831-ef3f123b3b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div[2]/div/div[2]/div[2]/div/button</value>
      <webElementGuid>3bde3194-081e-4062-b830-8eefcbe9f7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô hình xe Nissan Skyline GT-R R34 V-Spec 1:64 MiniGT'])[1]/following::button[1]</value>
      <webElementGuid>57fce9ac-33ed-4e1e-9f94-f8869ce6350d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm vào giỏ'])[1]/following::button[1]</value>
      <webElementGuid>c1d12b02-b31f-4977-94ff-4a222aa19b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô hình xe BMW i7 xDrive60 1:64 MiniGT'])[1]/preceding::button[1]</value>
      <webElementGuid>0053e3f6-33e6-4e30-9192-02e20863f7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm vào giỏ'])[3]/preceding::button[1]</value>
      <webElementGuid>ec05a115-5afa-4663-9bf4-0b0c7f3fe8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/button</value>
      <webElementGuid>912d18d2-bffb-499e-a9c8-a7902baf620b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @title = 'Buy now' and (text() = 'Thêm vào giỏ' or . = 'Thêm vào giỏ')]</value>
      <webElementGuid>b7644b23-5951-4561-8767-8869c52ee079</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
