<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Thm vo gi_img-loop image-product-loop b_e6f1b6</name>
   <tag></tag>
   <elementGuidId>412f9af1-d9d4-4acb-817b-e08a6582ff12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collection-body']/div/div[2]/div[3]/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0a09a30-e478-4eb7-935c-25d5298ada6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-loop image-product-loop bigloaded</value>
      <webElementGuid>13f5a73c-536f-42b6-b93f-fdfa719d7ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mô hình xe Nissan Skyline GT-R R34 V-Spec 1:64 MiniGT</value>
      <webElementGuid>4b3ae7df-ff83-4d89-a4ac-5a9309edbfdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/mo-hinh-xe-nissan-skyline-gt-r-r34-v-spec-1-64-minigt-bayside-blue__1__0afd9bcd1e70441a83f3ee9d5dde6672_large.jpg</value>
      <webElementGuid>520fe762-4886-4bb3-8d07-ef83c95ee2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>5ef6a5c1-e2e8-40e5-a455-7869f2e4f7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>a7409323-c804-4a72-b931-6e9b3af39969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/mo-hinh-xe-nissan-skyline-gt-r-r34-v-spec-1-64-minigt-bayside-blue__1__0afd9bcd1e70441a83f3ee9d5dde6672_large.jpg</value>
      <webElementGuid>e09aa083-ebe7-40c0-bd4c-a5113e17fe7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-body&quot;)/div[@class=&quot;col-sm-8 col-xs-12&quot;]/div[@class=&quot;row filter-here&quot;]/div[@class=&quot;content-product-list collection-list clearfix&quot;]/div[@class=&quot;pro-loop animation-tran&quot;]/div[@class=&quot;product-block  pro-new&quot;]/div[@class=&quot;product-img img-eff&quot;]/a[@class=&quot;image-resize&quot;]/img[@class=&quot;img-loop image-product-loop bigloaded&quot;]</value>
      <webElementGuid>b6adfabd-a28e-49ef-8da2-7b0b725d7c87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div[2]/div/div/a/img</value>
      <webElementGuid>d6658605-fde4-42c6-bf7a-08b153ff70c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mô hình xe Nissan Skyline GT-R R34 V-Spec 1:64 MiniGT']</value>
      <webElementGuid>697c3306-7657-4d96-9f50-816377a33190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/a/img</value>
      <webElementGuid>1ccea5d5-446d-4873-b330-b095c362348f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Mô hình xe Nissan Skyline GT-R R34 V-Spec 1:64 MiniGT' and @src = '//product.hstatic.net/200000726533/product/mo-hinh-xe-nissan-skyline-gt-r-r34-v-spec-1-64-minigt-bayside-blue__1__0afd9bcd1e70441a83f3ee9d5dde6672_large.jpg']</value>
      <webElementGuid>ce40b979-2f08-421a-87ce-dbc6a74eec25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
