<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Thm vo gi_img-loop lazyload image-produ_ad479d</name>
   <tag></tag>
   <elementGuidId>7e3e21a6-7570-48a3-8aa2-7ff9b64a866d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collection-body']/div/div[2]/div[3]/div[17]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0c7b120d-05d1-4a1e-880e-355e5f787adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-loop lazyload image-product-loop bigloaded</value>
      <webElementGuid>3669bab7-8986-40e9-be69-19b4d5f70de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE</value>
      <webElementGuid>973b24fd-1ebc-43f6-b34e-70cb0711aad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/mo-hinh-blind-box-moc-khoa-gau-bong-baby-three-v3-mini-baby-three__1__f7a2587de2614f32a28f6d6fdb778c0f_large.jpg</value>
      <webElementGuid>86354759-2777-452a-9f14-bf5af6b039d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>46e861a5-4896-4645-aed3-e10e8f2070ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>63d4bcc6-8090-412a-a568-85099234a73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/mo-hinh-blind-box-moc-khoa-gau-bong-baby-three-v3-mini-baby-three__1__f7a2587de2614f32a28f6d6fdb778c0f_large.jpg</value>
      <webElementGuid>457945b2-a523-4d1c-b3fe-e68d80f4e3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-body&quot;)/div[@class=&quot;col-sm-8 col-xs-12&quot;]/div[@class=&quot;row filter-here&quot;]/div[@class=&quot;content-product-list collection-list clearfix&quot;]/div[@class=&quot;pro-loop animation-tran&quot;]/div[@class=&quot;product-block  pro-new&quot;]/div[@class=&quot;product-img img-eff&quot;]/a[@class=&quot;image-resize&quot;]/img[@class=&quot;img-loop lazyload image-product-loop bigloaded&quot;]</value>
      <webElementGuid>1e89200c-428a-413f-ac4b-985dd06213f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div[17]/div/div/a/img</value>
      <webElementGuid>ba71d1d0-79d8-4358-8737-8702a400d313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE']</value>
      <webElementGuid>30ed3611-a840-4fa0-af67-6008f6405eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/a/img</value>
      <webElementGuid>7d9424e0-21d0-413a-8858-472580c3eac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE' and @src = '//product.hstatic.net/200000726533/product/mo-hinh-blind-box-moc-khoa-gau-bong-baby-three-v3-mini-baby-three__1__f7a2587de2614f32a28f6d6fdb778c0f_large.jpg']</value>
      <webElementGuid>e100aadb-fe63-417f-b889-f6e9a93643a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div[16]/div/div/a/img</value>
      <webElementGuid>c4c71d1b-5623-4a5f-ac99-b26fed892787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/a/img</value>
      <webElementGuid>66581e98-e233-41df-9d0d-bea4de0bb3c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
