<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(, , three, , )_img-loop image-pr_a47322</name>
   <tag></tag>
   <elementGuidId>20c5a2f8-d253-42d9-84ae-b3922c8bd244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-loop.image-product-loop.bigloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3099c7d3-da2d-4357-b936-8fca4261a1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-loop image-product-loop bigloaded</value>
      <webElementGuid>da91633d-68d9-42cf-8060-a4fb89bbd46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE</value>
      <webElementGuid>6ab6931d-97cf-4219-b26f-8cfd4f1cf182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/mo-hinh-blind-box-moc-khoa-gau-bong-baby-three-v3-mini-baby-three__1__f7a2587de2614f32a28f6d6fdb778c0f_large.jpg</value>
      <webElementGuid>eb8ff57c-2ed9-43c1-b87b-1272f7d1cddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>676dfb63-63f1-468f-9553-411741123ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>78605113-5cc6-4986-a119-6dd000a86ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/mo-hinh-blind-box-moc-khoa-gau-bong-baby-three-v3-mini-baby-three__1__f7a2587de2614f32a28f6d6fdb778c0f_large.jpg</value>
      <webElementGuid>a6ef8465-d7ce-404a-87ac-24c5006b7b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;content-product-list index-list row block-3&quot;]/div[@class=&quot;pro-loop animation-tran active&quot;]/div[@class=&quot;product-block  pro-new&quot;]/div[@class=&quot;product-img img-eff&quot;]/a[@class=&quot;image-resize&quot;]/img[@class=&quot;img-loop image-product-loop bigloaded&quot;]</value>
      <webElementGuid>ce1fd6b7-569d-47cb-932a-58fe38715e5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/div/a/img</value>
      <webElementGuid>74b4866a-c8fa-4a33-860e-b016222dfb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE']</value>
      <webElementGuid>e2f8b517-ffb7-4520-b575-ba33b0b16db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a/img</value>
      <webElementGuid>c877d5a3-8fa2-46cb-8b6f-6659f7869a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE' and @src = '//product.hstatic.net/200000726533/product/mo-hinh-blind-box-moc-khoa-gau-bong-baby-three-v3-mini-baby-three__1__f7a2587de2614f32a28f6d6fdb778c0f_large.jpg']</value>
      <webElementGuid>dea1d726-f17a-4663-8f4d-70002bbaf51d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
