<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thanh ton_site-close-handle</name>
   <tag></tag>
   <elementGuidId>179453e5-d797-48ab-870e-83d0b0f8c997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#site-close-handle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='site-close-handle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae0039b3-32d0-431c-9745-650971842643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>site-close-handle</value>
      <webElementGuid>301ed01e-8806-4e3c-b329-ca288108db26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-close-handle</value>
      <webElementGuid>08287850-24c0-4f50-935d-a2a291505e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>ef0e34c9-078a-4807-8cdf-afb5f07ff334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>b8275ff9-75c8-423d-9c38-c65b7526e715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-close-handle&quot;)</value>
      <webElementGuid>d8785fcb-11ad-4271-ac81-e9c54306e989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='site-close-handle']</value>
      <webElementGuid>a714425c-3ccb-4605-b1a4-49365b7f7ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-nav--mobile']/button</value>
      <webElementGuid>68beb81e-d7ca-43fa-be4a-fe42a76139b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh toán'])[2]/following::button[1]</value>
      <webElementGuid>632f060a-e2cc-44a1-b4a4-7ae696d71af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem giỏ hàng'])[1]/following::button[1]</value>
      <webElementGuid>099f635c-e874-497a-84f8-0f10a4ef7a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::button[1]</value>
      <webElementGuid>ac0b80dc-b5bd-4ed0-870e-606dbfa73748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông Báo'])[1]/preceding::button[2]</value>
      <webElementGuid>6f09c993-9241-4c51-bcee-07b9d133d701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>31394b5e-741d-420a-869c-9c3b74e2237e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'site-close-handle' and @title = 'Đóng']</value>
      <webElementGuid>b3533c82-5694-4059-b19d-4d452cea9a04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
