<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thm vo gi</name>
   <tag></tag>
   <elementGuidId>736bcb76-57d5-4d4b-a4ec-412e74633443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb5ecd59-7339-4e2b-a4c5-a983aaaf74c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3b3d10cd-f051-440d-8a0e-46f925b3525c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy now</value>
      <webElementGuid>1a622797-e178-4397-9064-277975699ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>c8e2f7dd-e05e-4393-ba24-e8c303cd2c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>buy_now('1142205293')</value>
      <webElementGuid>635eba08-c5a1-4fcc-b29d-e35a2787c1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm vào giỏ</value>
      <webElementGuid>e4f66111-f7db-4278-8d6f-a38c212ef64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-body&quot;)/div[@class=&quot;col-sm-8 col-xs-12&quot;]/div[@class=&quot;row filter-here&quot;]/div[@class=&quot;content-product-list collection-list clearfix&quot;]/div[@class=&quot;pro-loop animation-tran active&quot;]/div[@class=&quot;product-block  pro-new&quot;]/div[@class=&quot;product-detail clearfix&quot;]/div[@class=&quot;quick-action&quot;]/div[@class=&quot;button-add&quot;]/button[@class=&quot;action&quot;]</value>
      <webElementGuid>05ac1524-7c97-445f-85ba-b81e7a9f1ed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>dc723dc1-a282-424b-a2d1-7f353f4149a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>5815082e-62cd-4079-bd8a-486d5b63ab0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE'])[1]/following::button[1]</value>
      <webElementGuid>ec377bb7-22e6-43ab-a9e3-382b7900a91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiêu đề Z-A'])[1]/following::button[1]</value>
      <webElementGuid>eeac10d9-fd7d-4374-b5a7-fa92b21b189c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô hình Blind box Gấu bông Take Me Out Zipper Bag BABY THREE'])[1]/preceding::button[1]</value>
      <webElementGuid>d002ef76-1e6d-4178-8b1c-74ae146b3c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm vào giỏ'])[2]/preceding::button[1]</value>
      <webElementGuid>46937067-475e-41ab-af2a-fb53c3ae7309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thêm vào giỏ']/parent::*</value>
      <webElementGuid>294b028e-19fe-4528-a134-2c91f8e217b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>9d3c0bf5-00bf-4431-926a-890f2794fc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @title = 'Buy now' and (text() = 'Thêm vào giỏ' or . = 'Thêm vào giỏ')]</value>
      <webElementGuid>8b59a605-fc8c-49de-816a-e1872d4b2452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
