<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tiu  Z-A_img-loop image-product-loop bigloaded</name>
   <tag></tag>
   <elementGuidId>bfe46bf0-3409-4933-b4e8-914055dddb82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-loop.image-product-loop.bigloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collection-body']/div/div[2]/div[3]/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9bff843d-fdd8-4b0e-ab08-6ea77f9ad6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-loop image-product-loop bigloaded</value>
      <webElementGuid>9342b5b8-8c43-4421-b5ce-3a6998df8882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE</value>
      <webElementGuid>b05a899c-e76d-43f4-b0fe-b9ec37e72d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/mo-hinh-blind-box-moc-khoa-gau-bong-baby-three-v3-mini-baby-three__1__f7a2587de2614f32a28f6d6fdb778c0f_large.jpg</value>
      <webElementGuid>2de54b30-4e6c-4d01-b66e-c07cd5d5b819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>9f8d922a-b529-47fa-bf48-39543a296e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>2cdb89e9-5552-4d24-bab8-4062e560114c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/200000726533/product/mo-hinh-blind-box-moc-khoa-gau-bong-baby-three-v3-mini-baby-three__1__f7a2587de2614f32a28f6d6fdb778c0f_large.jpg</value>
      <webElementGuid>3701e944-ed99-4c16-b6ae-4caeab69e6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-body&quot;)/div[@class=&quot;col-sm-8 col-xs-12&quot;]/div[@class=&quot;row filter-here&quot;]/div[@class=&quot;content-product-list collection-list clearfix&quot;]/div[@class=&quot;pro-loop animation-tran&quot;]/div[@class=&quot;product-block  pro-new&quot;]/div[@class=&quot;product-img img-eff&quot;]/a[@class=&quot;image-resize&quot;]/img[@class=&quot;img-loop image-product-loop bigloaded&quot;]</value>
      <webElementGuid>0f240daf-858d-453b-beca-a2bc8dacd326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-body']/div/div[2]/div[3]/div/div/div/a/img</value>
      <webElementGuid>aab2ce82-28d2-475e-866e-cd9f4996d5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE']</value>
      <webElementGuid>e5653e7e-4f41-4790-9ffd-9355b472eaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/img</value>
      <webElementGuid>ecb9b626-46b1-4aae-bccc-c764928faf50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Mô hình Blind box Móc khóa Gấu bông Baby Three V3 Mini BABY THREE' and @src = '//product.hstatic.net/200000726533/product/mo-hinh-blind-box-moc-khoa-gau-bong-baby-three-v3-mini-baby-three__1__f7a2587de2614f32a28f6d6fdb778c0f_large.jpg']</value>
      <webElementGuid>873bff7a-1b56-4444-b6c5-2d93f4bd4119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
